### ISSUE TITLE
riscv64-unknown-elf toolchain

### ISSUE THREAD

**Issue by wezm** [riscv-rust/longan-nano#1]
Hi, where does one acquire the `riscv64-unknown-elf` toolchain mentioned in `.cargo/config`? Ideally I'd like to build the toolchain from source.

https://github.com/riscv-rust/riscv-rust-toolchain says it's obsolete and links to https://github.com/riscv-rust/rust, which is a 404.

**Comment by wezm** [comment]
Nevermind, I worked it out. gdb 8.2+ have built in support: https://www.gnu.org/software/gdb/news/

**Comment by Disasm** [comment]
If it will not work, try the toolchain from SiFive: https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.1.0-2019.01.0-x86_64-linux-ubuntu14.tar.gz
