### ISSUE TITLE
Huge binaries after objcopy

### ISSUE THREAD

**Issue by simonsilvalauinger** [riscv-rust/longan-nano#14]
Hi there,
thank you for creating this small project as help to start a rust project. on longan-nano.
Unfortunatelly I have a problem with objcopy trying to use the dfu-util method. Using `riscv-nuclei-elf-objcopy -O binary target/riscv32imac-unknown-none-elf/release/examples/blinky blinky.bin` results in an 385M sized file! Any other example has a similar result file size.
Does somebody has a clue how to solve this behaviour?

Thank you
Simon

**Comment by Disasm** [comment]
You can try `beta` or `nightly` compiler to solve the issue. See also: https://github.com/icebreaker-fpga/icebreaker-litex-examples/issues/6#issuecomment-667601893

**Comment by simonsilvalauinger** [comment]
Thank you for your help, this solved the problem :)
