### ISSUE TITLE
memory.x GD32VF103CB vs C8

### ISSUE THREAD

**Issue by BartMassey** [riscv-rust/longan-nano#6]
Sadly, there seem to be Longan Nano boards out there with both the GD32VF103C8 and GD32VF103CB processors. The C8 has 64K/20K, the CB (what I have) has 128K/32K. The `memory.x` in this package is for the C8, which is conservative and works until you run out of memory. It would be nice to also include the CB version (just change the `LENGTH` entries; verified that this works) and put a note in the `README` or something…

I noticed this because the Ferris example compiled for dev is about 67K.

**Comment by Disasm** [comment]
Fixed in 27538e3f112960c27252faed785babc6b1e29f8c
With the latest stable Rust (1.41.0) the examples fit in a flash, though.

**Comment by Disasm** [comment]
My bad, that was a build in workspace with 
```
[profile.dev]
opt-level = "s"
```
Debug build fails without this hack.
