### ISSUE TITLE
LCD width is defined with wrong value

### ISSUE THREAD

**Issue by elfmimi** [riscv-rust/longan-nano#7]
https://github.com/riscv-rust/longan-nano/blob/7186bcf4b7b49af74aeae743bec0b26d781f50b9/src/lcd.rs#L81
It should be 160.

I was wondering why Ferris is not being displayed at the center of the screen.
Above was the cause.

**Comment by Disasm** [comment]
Hmm, for some reason the correct rectangle for clearing the screen is `Rectangle::new(Coord::new(1, 0), Coord::new(width, height - 1))`. X coordinate is off by one.

**Comment by elfmimi** [comment]
Oh, I did not notice that.
Yup, look here.
https://github.com/riscv-rust/longan-nano/blob/7186bcf4b7b49af74aeae743bec0b26d781f50b9/src/lcd.rs#L72
